
m = smtb.pbpk.buildPBPKmodelTemplate('acat',false,...
    'pkmodel','pbpk');
me = export(m);

fup = 0.01;
[inputs,v] = smtb.pbpk.getPBPKVariant([], ...
    'species','human',...
    'compound','test compound',...
    'distribution','pbpk',... %
    'mw',450,...
    'logP',3.5,...
    'sol_mgmL',1*10,... %  No ACAT so not useful
    'Peff0',1.23*10,... % No ACAT so not useful
    'sol_pH',-1,... % NO ACAT so not useful
    'FaSSIF',0,...
    'FeSSIF',0,...
    'FaSSGF',0,...
    'SF',20,...
    'Deff',5e-7,...
    'Acidic_pka',[],...
    'Basic_pka',[],...
    'CLint',10,...
    'CLint_fuinc',1,... % fraction unbound in microsome/hepatocyte assay
    'fup',fup,...
    'B2P',1,...
    'fub','fup/BP',...
    'ASF_method','Theoretical_SAV',...
    'para_abs','off',...
    'fup_type','experimental',...
    'RenalFiltration','off',...
    'acatFlag', false);

v.addcontent({'parameter', 'ka', 'value', 1.7});



%vHuman = v(strcmpi(v(:,1),'Human'),:);

x0 = smtb.simbio.initialValuesFromVariant(me, v(1));


%vHuman{2}{5}{4} = 1.7; % Regulate the Ka parameter. Currently not an option 
% to set in parameterize function

d = me.getdose('SC'); 
d.Amount = 100;
d.Interval = 24; 
d.RepeatCount = 0;
me.SimulationOptions.StopTime = 48; % set simulation stop time at 24 hours

sd = simulate(me,x0, d); % use simulate, not sbiosimulate
cp = selectbyname(sd,'plasma.drug');
figure('DefaultAxesFontSize', 14);
plot(cp.Time,fup*cp.Data, 'LineWidth',3, 'DisplayName', 'No ACAT- SC'); 
hold on;
if exist("cp.mat", 'file')
load('cp.mat');
plot(cp.Time, fup*cp.Data, 'LineWidth',2, 'LineStyle','--', ...
    'color', 'c', 'DisplayName','ACAT - PO');
end
legend();
title('Human PK');
xlabel('Time, hours');
ylabel(sprintf('%s, %s', cp.DataInfo{1}.Name,cp.DataInfo{1}.Units));
% res_ex = calculate_time_series_simulation_results(sd,me, ...
%     d, 'fup', fup);



