

% Build the PBPK base model
m = BuildPBPKStructure;
me = export(m);

% Now parameterize the variants with no DrugProps - essentially you need to
% define every input as something user-defined
[~,inputs,v] = parameterizePBPK(m,[],'species','Human',...
    'compound','test compound',...
    'mw',450,...
    'logP',3.5,...
    'sol_mgmL',1*10,...
    'Peff',1.23*10,...
    'sol_pH',-1,...
    'FaSSIF',0,...
    'FeSSIF',0,...
    'FaSSGF',0,...
    'SF',20,...
    'Deff',5e-7,...
    'acidic_pka',[],...
    'basic_pka',[],...
    'clint_human',10,...
    'fuinc_human',1,... % fraction unbound in microsome/hepatocyte assay
    'fup_human',0.01,...
    'bp_human',1,...
    'fub_human','fup/BP',...
    'ASF_method','Theoretical_SAV',...
    'para_abs','off',...
    'fup_type','experimental',...
    'RenalFiltration','off');

%% This section is an example running with an exported SimBiology model

% To run with an exported model, you need to select the proper variant from
% variable "v" - A SIMBIOLOGY VARIANT WILL NOT WORK WITH THIS

% run with human as an example - get human variant content from variable v
v_human_ex = v(strcmpi(v(:,1),'Human Fasted'),:);

% applyVariant takes the 1x4 cell arrays and overwrites the original model
% values - note this is only passing the 1x4 cell arrays
me = applyVariant(me,v_human_ex{2});
d_po_ex = me.getdose('PO'); % note this is not a simbiology dose object
d_po_ex.Amount = 100;
d_po_ex.Interval = 24; % recall the 
% calculate_time_series_simulation_results requires a dose interval
me.SimulationOptions.StopTime = 24; % set simulation stop time at 24 hours

sd_human_ex = simulate(me,d_po_ex); % use simulate, not sbiosimulate
cp = selectbyname(sd_human_ex,'plasma.drug');
figure
plot(cp.Time,cp.Data)
title('Human PK - exported model')

%res_ex = calculate_time_series_simulation_results(sd_human_ex,me,d_po_ex);

save('cp.mat', 'cp');

