function inputs = faSSGFsolFromDrugProps (inputs, dp)
if contains(strrep(strrep(lower(inputs.FaSSGF_source),' ',''),'_',''), ...
        'qsaradmet')
    inputs.FaSSGF_source = 'QSAR ADMET';
end
switch strrep(strrep(lower(inputs.FaSSGF_source),' ',''),'_','')
    case {'default','admet','qsaradmet'}
        idx = contains({dp.sol.source},'ADMET')&strcmpi({dp.sol.matrix}, ...
            'FaSSGF');
        inputs.FaSSGF_source = dp.sol(idx).source;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix},'FaSSGF')).pH = ...
            dp.sol(idx).pH;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix},'FaSSGF')).value = ...
            dp.sol(idx).value;
    case {'kate','measured'}
        try
            idx = find(contains({dp.sol.source},'KATE', ...
                'IgnoreCase',true)&contains({dp.sol.matrix},'FaSSGF', ...
                'IgnoreCase',true));
            if ~isempty(idx)
                inputs.FaSSGF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSGF')).pH = mean([dp.sol(idx).pH], 'omitnan');
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSGF')).value = mean([dp.sol(idx).value], 'omitnan');
            else
                idx = contains({dp.sol.source}, ...
                    'ADMET')&strcmpi({dp.sol.matrix},'FaSSGF');
                inputs.FaSSGF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSGF')).pH = dp.sol(idx).pH;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSGF')).value = dp.sol(idx).value;
            end
        catch
            idx = contains({dp.sol.source}, ...
                'ADMET')&strcmpi({dp.sol.matrix},'FaSSIF');
            inputs.FaSSIF_source = dp.sol(idx).source;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSIF')).pH = dp.sol(idx).pH;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSIF')).value = dp.sol(idx).value;
        end
    case 'userdefined' % TODO: should be moved to parseInputs.m 
        % since its sets inputs.bio_sol even in absence of drug props
        if isempty(inputs.FaSSGF_pH)
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSGF')).pH = 1.6;
        end
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FaSSGF')).value = inputs.FaSSGF;
    otherwise, error(['Unrecognized biorelevant solubility source.  ' ...
            'Please choose from "ADMET" or "KATE."'])
end
inputs.FaSSGF = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FaSSGF')).value;
inputs.FaSSGF_pH = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FaSSGF')).pH;
end