function inputs = faSSIFsolFromDrugProps(inputs, dp)
if contains(strrep(strrep(lower(inputs.FaSSIF_source),' ',''),'_',''), ...
        'qsaradmet')
    inputs.FaSSIF_source = 'QSAR ADMET';
end
switch strrep(strrep(lower(inputs.FaSSIF_source),' ',''),'_','')
    case {'default','kate','measured','katefassif','katefassifht'}
        try
            idx = find(contains({dp.sol.source},'KATE', ...
                'IgnoreCase',true)&contains({dp.sol.matrix}, ...
                'FaSSIF','IgnoreCase',true));
            if ~isempty(idx)
                inputs.FaSSIF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSIF')).pH = mean([dp.sol(idx).pH], 'omitnan');
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSIF')).value = mean([dp.sol(idx).value], ...
                    'omitnan');
            else
                idx = contains({dp.sol.source}, ...
                    'ADMET')&strcmpi({dp.sol.matrix},'FaSSIF');
                inputs.FaSSIF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSIF')).pH = dp.sol(idx).pH;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FaSSIF')).value = dp.sol(idx).value;
            end
        catch
            idx = contains({dp.sol.source}, ...
                'ADMET')&strcmpi({dp.sol.matrix},'FaSSIF');
            inputs.FaSSIF_source = dp.sol(idx).source;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSIF')).pH = dp.sol(idx).pH;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSIF')).value = dp.sol(idx).value;
        end
    case {'admet','qsaradmet'}
        idx = contains({dp.sol.source}, ...
            'ADMET')&strcmpi({dp.sol.matrix},'FaSSIF');
        inputs.FaSSIF_source = dp.sol(idx).source;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FaSSIF')).pH = dp.sol(idx).pH;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FaSSIF')).value = dp.sol(idx).value;
    case 'userdefined' %TODO: should be moved to parseInputs.m
        % since its sets inputs.bio_sol even in absence of drug props
        if isempty(inputs.FaSSIF_pH)
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FaSSIF')).pH = 6.5;
        end
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FaSSIF')).value = inputs.FaSSIF;
    otherwise, error(['Unrecognized biorelevant solubility source. ' ...
            ' Please choose from "ADMET" or "KATE."'])
end
inputs.FaSSIF = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FaSSIF')).value;
inputs.FaSSIF_pH = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FaSSIF')).pH;


end