function inputs = feSSIFsolFromDrugProps(inputs, dp)
if contains(strrep(strrep(lower(inputs.FeSSIF_source),' ',''),'_',''), ...
        'qsaradmet')
    inputs.FeSSIF_source = 'QSAR ADMET';
end
switch strrep(strrep(lower(inputs.FeSSIF_source),' ',''),'_','')
    case {'default','admet','qsaradmet'}
        idx = contains({dp.sol.source}, ...
            'ADMET')&strcmpi({dp.sol.matrix},'FeSSIF');
        inputs.FeSSIF_source = dp.sol(idx).source;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FeSSIF')).pH = dp.sol(idx).pH;
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FeSSIF')).value = dp.sol(idx).value;
    case {'kate','measured'}  
        try
            idx = find(contains({dp.sol.source},'KATE', ...
                'IgnoreCase',true)&contains({dp.sol.matrix},'FeSSIF', ...
                'IgnoreCase',true));
            if ~isempty(idx)
                inputs.FeSSIF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FeSSIF')).pH = mean([dp.sol(idx).pH], 'omitnan');
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FeSSIF')).value = mean([dp.sol(idx).value], ...
                    'omitnan');
            else
                idx = contains({dp.sol.source}, ...
                    'ADMET')&strcmpi({dp.sol.matrix},'FeSSIF');
                inputs.FeSSIF_source = dp.sol(idx).source;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FeSSIF')).pH = dp.sol(idx).pH;
                inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                    'FeSSIF')).value = dp.sol(idx).value;
            end
        catch
            idx = contains({dp.sol.source}, ...
                'ADMET')&strcmpi({dp.sol.matrix},'FeSSIF');
            inputs.FeSSIF_source = dp.sol(idx).source;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FeSSIF')).pH = dp.sol(idx).pH;
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FeSSIF')).value = dp.sol(idx).value;
        end
    case 'userdefined' % %TODO: should be moved to parseInputs.m
        % since its sets inputs.bio_sol even in absence of drug props
        if isempty(inputs.FeSSIF_pH)
            inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
                'FeSSIF')).pH = 5;
        end
        inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
            'FeSSIF')).value = inputs.FeSSIF;
    otherwise, error(['Unrecognized biorelevant solubility source.' ...
            '  Please choose from "ADMET" or "KATE."'])
end
inputs.FeSSIF = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FeSSIF')).value;
inputs.FeSSIF_pH = inputs.bio_sol(strcmpi({inputs.bio_sol.matrix}, ...
    'FeSSIF')).pH;

end