function mPD = tolerance()
m1 = sbiomodel('toleranceModel');
cmpProps = {'Name', 'Value', 'Units', 'Constant'};
cmps = {
    {'pd', 1, 'milliliter', 1},...
    };
addcompartments(m1, cmps, cmpProps);

spProps = {'CompName', 'Name', 'Value', 'Units'};
species = {
    {'pd', 'P1', 1, 'nanomole/milliliter'},...
    {'pd', 'P2', 1, 'nanomole/milliliter'},...
    {'pd', 'TE', 0, 'molecule'}
    };
addspecies(m1, species, spProps)

% 1. M1 <-> M2, null -> M1,
rnSet1 = {
    {'P1 -> null', 'kout_1 * P1','R_deg_P1'},...
    {'TE -> TE + P1', 'kin_1 * drug_effect', 'R_syn_P1'},...
    {'P2 -> null', 'kout_2 * P2','R_deg_P2'},...
    {'P1 -> P1 + P2', 'kin_2 * (P1/oneP1)^delta','R_syn_P2'},...
    };
prSet1 = {
    {'delta',  5, "dimensionless", "", 1}, ...
    {'drug_effect', 1, 'dimensionless', "", 0},...
    {'oneTE', 1, 'molecule', "", 1},...
    {'oneP1', 1, 'nanomole/(milliliter)', "", 1},...
    {'Imax', 1, "dimensionless", "", 1},...
    {'epsilon', 5, "dimensionless", "", 1},...
    {'kin_1',0.01, 'nanomole/(milliliter * hour)', "syn", 1},...
    {'kin_2',0.005, 'nanomole/(milliliter *hour)', "syn", 1},...
    {'kout_1',0.01, '1/hour', "deg", 1},...
    {'kout_2',0.005, '1/hour', "deg", 1},...
    };


% Reactions
rnProps = {'Reaction', 'ReactionRate', 'Name'};
reactions = rnSet1;
addreactions(m1, reactions, rnProps);

% Parameters
paramProps = {'Name', 'Value', 'Units', 'Tag', 'Constant'};
params = prSet1;
addparameters(m1, params, paramProps);

addrule(m1,'drug_effect = 1 + (Imax * (pd.TE/oneTE))', ...
    'RuleType','RepeatedAssignment');

% adddose(m1,sbiodose('te_dose','Target','pd.TE','Amount', 0, ...
%     'AmountUnits','molecule', 'Interval', 24, ...
%     'TimeUnits','hour','RateUnits','molecule/hour', ...
%     'RepeatCount',0));

m1.getequations
mPD = m1;
clearvars -except mPD;

cs = getconfigset(mPD);
cs.CompileOptions.DimensionalAnalysis = true;
cs.CompileOptions.UnitConversion = true;
cs.TimeUnits = 'hour';

addparameter(mPD,'clTE','Value',0,'ValueUnits','1/hour');
addreaction(mPD,'TE -> null','Name',...
    'R_clTE','ReactionRate','TE * clTE');
end
