function mPD = transduction()
m1 = sbiomodel('transductionModel');
cmpProps = {'Name', 'Value', 'Units', 'Constant'};
cmps = {
    {'pd', 1, 'milliliter', 1},...
    };
addcompartments(m1, cmps, cmpProps);

spProps = {'CompName', 'Name', 'Value', 'Units'};
species = {
    {'pd', 'M1', 1, 'nanomole/milliliter'},...
    {'pd', 'M2', 1, 'nanomole/milliliter'},...
    {'pd', 'M3', 1, 'nanomole/milliliter'},...
    {'pd', 'M4', 1, 'nanomole/milliliter'},...
    {'pd', 'TE', 0, 'molecule'}
    };
addspecies(m1, species, spProps)

% 1. M1 <-> M2, null -> M1,
rnSet1 = {
    {'M1 -> M2', 'k * M1','R_conv_M1_M2'},...
    {'M4 + TE -> M1 + TE + M4',...
        'k  * oneM4* drug_effect / (M4 /oneM4)^sigma',...
        'R_synthesis_M1'},...
    {'M2 -> M3', 'k * M2','R_conv_M2_M3'},...
    {'M3 -> M4', 'k * M3','R_conv_M3_M4'},...
    {'M4 -> null', 'k * M4', 'R_deg_M4'},...
    };
prSet1 = {
    {'k',  1/36, "1 / hour", "deg", 1}, ...
    {'drug_effect', 1, 'dimensionless', "", 0},...
    {'oneTE', 1, 'molecule', "", 1},...
    {'Imax', 1, "dimensionless", "", 1},...
    {'sigma', 0.25, "dimensionless", "", 1},...
    {'oneM4',1, 'nanomole/milliliter', "", 1},...
    };




% Reactions
rnProps = {'Reaction', 'ReactionRate', 'Name'};
reactions = rnSet1;
addreactions(m1, reactions, rnProps);

% Parameters
paramProps = {'Name', 'Value', 'Units', 'Tag', 'Constant'};
params = prSet1;
addparameters(m1, params, paramProps);

addrule(m1,'drug_effect = 1 + (Imax * (pd.TE/oneTE))', ...
    'RuleType','RepeatedAssignment');

% adddose(m1,sbiodose('te_dose','Target','pd.TE','Amount', 0, ...
%     'AmountUnits','molecule', 'Interval', 24, ...
%     'TimeUnits','hour','RateUnits','molecule/hour', ...
%     'RepeatCount',0));

%m1.getequations
mPD = m1;
clearvars -except mPD;

cs = getconfigset(mPD);
cs.CompileOptions.DimensionalAnalysis = true;
cs.CompileOptions.UnitConversion = true;
cs.TimeUnits = 'hour';

addparameter(mPD,'clTE','Value',0,'ValueUnits','1/hour');
addreaction(mPD,'TE -> null','Name',...
    'R_clTE','ReactionRate','TE * clTE');
end

