function mPD = tumor()
m1 = sbiomodel('tumorModel');
cmpProps = {'Name', 'Value', 'Units', 'Constant'};
cmps = {
    {'pd', 1, 'milliliter', 1},...
    };
addcompartments(m1, cmps, cmpProps);

spProps = {'CompName', 'Name', 'Value', 'Units'};
species = {
    {'pd', 'T', 1, 'nanomole/milliliter'},...
    {'pd', 'Z1', 0, 'nanomole/milliliter'},...
    {'pd', 'Z2', 0, 'nanomole/milliliter'},...
    {'pd', 'Z3', 0, 'nanomole/milliliter'},...
    {'pd', 'C', 1, 'nanomole/milliliter'},...
    {'pd', 'TE', 0, 'molecule'}
    };
addspecies(m1, species, spProps)

% 1. M1 <-> M2, null -> M1,
rnSet1 = {
    {'T -> Z1', 'drug_effect * T','R_deg_T'},...
    {'null -> T', 'lambda0 * T','R_syn_T'},...
    {'Z1 -> Z2', 'k  * Z1','R_deg_Z1'},...
    {'Z2 -> Z3', 'k * Z2','R_deg_Z2'},...
    {'Z3 -> null', 'k * Z3','R_deg_Z3'},...
    {'null -> C', 'lambda0 * C','R_syn_C'},...
    };
prSet1 = {
    {'k',  3e-4, "1 / hour", "deg", 1}, ...
    {'drug_effect', 1, '1/hour', "", 0},...
    {'oneTE', 1, 'molecule', "", 1},...
    {'Imax', 0.003, "1/hour", "", 1},...
    {'lambda0', 1e-4, "1/hour", "", 1},...
    {'TGI', 0, 'dimensionless', "", 0},...
    {'Ttot', 1, 'nanomole/milliliter',"", 0},...
    {'oneT', 1, 'nanomole/milliliter',"", 1},...
    };




% Reactions
rnProps = {'Reaction', 'ReactionRate', 'Name'};
reactions = rnSet1;
addreactions(m1, reactions, rnProps);

% Parameters
paramProps = {'Name', 'Value', 'Units', 'Tag', 'Constant'};
params = prSet1;
addparameters(m1, params, paramProps);

addrule(m1,'drug_effect = Imax * (pd.TE/oneTE)', ...
    'RuleType','RepeatedAssignment');

addrule(m1,'Ttot = pd.T + pd.Z1 + pd.Z2 + pd.Z3', ...
    'RuleType','RepeatedAssignment');

addrule(m1,'TGI = 100 * (1 - (1-Ttot/oneT)/(1 - pd.C/oneT))', ...
    'RuleType','RepeatedAssignment');


m1.getequations
mPD = m1;
clearvars -except mPD;

cs = getconfigset(mPD);
cs.CompileOptions.DimensionalAnalysis = true;
cs.CompileOptions.UnitConversion = true;
cs.TimeUnits = 'hour';

addparameter(mPD,'clTE','Value',0,'ValueUnits','1/hour');
addreaction(mPD,'pd.TE -> null','Name',...
    'R_clTE','ReactionRate','pd.TE * clTE');
end

